export enum PaymentState {
    TRACKER_STARTED = "TRACKER_STARTED",
    TRACKER_AUTHORIZED = "TRACKER_AUTHORIZED",
    TRACKER_ENROLLED = "TRACKER_ENROLLED",
    TRACKER_ENDED = "TRACKER_ENDED",
    TRACKER_CANCELLED = "TRACKER_CANCELLED",
    TRACKER_EXPIRED = "TRACKER_EXPIRED",
    TRACKER_REFUNDED = "TRACKER_REFUNDED",
    TRACKER_PARTIAL_REFUND = "TRACKER_PARTIAL_REFUND",
    TRACKER_DISPUTED = "TRACKER_DISPUTED",
    TRACKER_REVERSED = "TRACKER_REVERSED",
    TRACKER_VOIDED = "TRACKER_VOIDED"
};
