export enum EnrollmentAuthenticationStatus {
    REQUIRED = "REQUIRED",
    FRICTIONLESS = "FRICTIONLESS",
    ATTEMPTED = "ATTEMPTED",
    UNAVAILABLE = "UNAVAILABLE",
    FAILED = "FAILED",
    REJECTED = "REJECTED",
    NOT_ELIGIBLE = "NOT_ELIGIBLE"
};
